/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ranguel (https://sketchfab.com/Roberto.De.Jesus.Gonzalez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steam-controller-2-concept-7ebaa30f05f042489f2978b5c5df8177
Title: Steam Controller 2 Concept
*/

import React, { JSX } from 'react'
import { useGLTF, Float } from '@react-three/drei'
import * as THREE from 'three'

export default function Controller(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/controller.glb')
  return (
    <Float
      speed={1} // Animation speed, defaults to 1
      rotationIntensity={0.09} // XYZ rotation intensity, defaults to 1
      floatIntensity={0.09} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
      floatingRange={[-0.999, -0.101]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
      dispose={null}
    >
      <group {...props} >
        <mesh
          castShadow
          geometry={(nodes.Object_5 as THREE.Mesh).geometry}
          material={materials.Controller_plastic}
        />
        <mesh
          castShadow
          geometry={(nodes.Object_6 as THREE.Mesh).geometry}
          material={materials.Smooth_Plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_8 as THREE.Mesh).geometry}
          material={materials.Trigger_plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_9 as THREE.Mesh).geometry}
          material={materials.Smooth_Plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_11 as THREE.Mesh).geometry}
          material={materials['Touch-PAD']}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_12 as THREE.Mesh).geometry}
          material={materials.Button_STEAM_high}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_14 as THREE.Mesh).geometry}
          material={materials['Touch-PAD']}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_15 as THREE.Mesh).geometry}
          material={materials.Button_STEAM_high}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_17 as THREE.Mesh).geometry}
          material={materials.Smooth_Plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_18 as THREE.Mesh).geometry}
          material={materials.Button_high}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_20 as THREE.Mesh).geometry}
          material={materials.Trigger_plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_21 as THREE.Mesh).geometry}
          material={materials.Smooth_Plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_23 as THREE.Mesh).geometry}
          material={materials.Smooth_Plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_25 as THREE.Mesh).geometry}
          material={materials.Joystick_plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_26 as THREE.Mesh).geometry}
          material={materials.Joystick_rubber}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_28 as THREE.Mesh).geometry}
          material={materials.Metal}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_30 as THREE.Mesh).geometry}
          material={materials['Touch-PAD']}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_32 as THREE.Mesh).geometry}
          material={materials.Trigger_plastic}

        />
        <mesh
          castShadow
          geometry={(nodes.Object_33 as THREE.Mesh).geometry}
          material={materials.Smooth_Plastic}

        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/controller.glb')
