/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cubemodelex (https://sketchfab.com/cubemodelex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jbl-tour-one-m3-black-45f0b3ccbee84492a05998d5daecff16
Title: JBL Tour One M3 (Black)
*/

import React from 'react'
import { useGLTF, Float } from '@react-three/drei'
import { MathProps, ReactProps, EventHandlers, InstanceProps } from '@react-three/fiber'
import { Mutable, Overwrite } from '@react-three/fiber/dist/declarations/src/core/utils'
import { Group, Object3DEventMap } from 'three'
import * as THREE from 'three'

export default function Headphones(props: React.JSX.IntrinsicAttributes & Mutable<Overwrite<Partial<Overwrite<Group<Object3DEventMap>, MathProps<Group<Object3DEventMap>> & ReactProps<Group<Object3DEventMap>> & Partial<EventHandlers>>>, Omit<InstanceProps<Group<Object3DEventMap>, Group>, "object">>>) {
    const { nodes, materials } = useGLTF('/models/headphones.glb')
    return (
        <Float
            speed={1} // Animation speed, defaults to 1
            rotationIntensity={0.1} // XYZ rotation intensity, defaults to 1
            floatIntensity={0.1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
            floatingRange={[-0.1, -0.1]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
            dispose={null}
        >
            <group {...props} args={[]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_4 as THREE.Mesh).geometry}
                    material={materials.Button_Glossy}
                    position={[0.033, 0.011, 0.02]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_6 as THREE.Mesh).geometry}
                    material={materials.Aluminum}
                    position={[0, 0.103, 0.005]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_8 as THREE.Mesh).geometry}
                    material={materials.Leather}
                    position={[0, 0.169, 0.005]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_10 as THREE.Mesh).geometry}
                    material={materials.Speacker_Mesh}
                    position={[0, 0.046, 0]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_12 as THREE.Mesh).geometry}
                    material={materials.Power_LED}
                    position={[0.021, 0.005, -0.019]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_14 as THREE.Mesh).geometry}
                    material={materials.JBL_Logo_Inner}
                    position={[0, 0.026, 0.012]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_16 as THREE.Mesh).geometry}
                    material={materials.Metal}
                    position={[0, 0.022, 0.03]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_18 as THREE.Mesh).geometry}
                    material={materials.Port_Plastic}
                    position={[0.022, 0.006, -0.01]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_20 as THREE.Mesh).geometry}
                    material={materials.Port_Aluminum_2}
                    position={[0.021, 0.005, -0.011]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_22 as THREE.Mesh).geometry}
                    material={materials.Port_Aluminum}
                    position={[0.022, 0.006, -0.01]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_24 as THREE.Mesh).geometry}
                    material={materials.Button_Logo}
                    position={[-0.028, 0.003, 0.012]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_26 as THREE.Mesh).geometry}
                    material={materials.Leather_Inner}
                    position={[0, 0.049, 0]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_28 as THREE.Mesh).geometry}
                    material={materials.JBL_Logo_Outer}
                    position={[0, 0.026, 0.012]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_30 as THREE.Mesh).geometry}
                    material={materials.Plastic}
                    position={[0, 0.034, -0.001]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_32 as THREE.Mesh).geometry}
                    material={materials.Ring}
                    position={[0, 0.034, -0.001]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_34 as THREE.Mesh).geometry}
                    material={materials.Black}
                    position={[0, 0.023, -0.002]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_36 as THREE.Mesh).geometry}
                    material={materials.RL_Icon}
                    position={[0, 0.046, 0]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_38 as THREE.Mesh).geometry}
                    material={materials.Icons}
                    position={[0, 0.051, -0.031]}
                    scale={0.01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={(nodes.Object_40 as THREE.Mesh).geometry}
                    material={materials.Metal_2}
                    position={[0, 0.022, 0.03]}
                    scale={0.01}
                />
            </group>
        </Float>
    )
}

useGLTF.preload('/models/headphones.glb')
