/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-13-inch-2020-efab224280fd4c3993c808107f7c0b38
Title: Macbook Pro 13 inch 2020
*/

import React from 'react'
import { useGLTF, Float } from '@react-three/drei'
import { MathProps, ReactProps, EventHandlers, InstanceProps } from '@react-three/fiber'
import { Mutable, Overwrite } from '@react-three/fiber/dist/declarations/src/core/utils'
import { Group, Object3DEventMap } from 'three'
import * as THREE from 'three'

export default function Mac(props: React.JSX.IntrinsicAttributes & Mutable<Overwrite<Partial<Overwrite<Group<Object3DEventMap>, MathProps<Group<Object3DEventMap>> & ReactProps<Group<Object3DEventMap>> & Partial<EventHandlers>>>, Omit<InstanceProps<Group<Object3DEventMap>, Group>, "object">>>) {
    const { nodes, materials } = useGLTF('/models/macbook.glb')
    return (
        <Float
            speed={1} // Animation speed, defaults to 1
            rotationIntensity={0.1} // XYZ rotation intensity, defaults to 1
            floatIntensity={0.1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
            floatingRange={[-0.1, -0.1]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
            dispose={null}
        >
            <group {...props} args={[]}>
                <group name="Sketchfab_Scene">
                    <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                        <group name="root">
                            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                                <group name="Bevels_2" position={[0, 0.008, -0.104]} scale={0.275}>
                                    <mesh
                                        name="Object_4"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_4 as THREE.Mesh).geometry}
                                        material={materials.Black_Glass}
                                    />
                                    <mesh
                                        name="Object_5"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_5 as THREE.Mesh).geometry}
                                        material={materials.Black_Plastic}
                                    />
                                    <mesh
                                        name="Object_6"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_6 as THREE.Mesh).geometry}
                                        material={materials.Glass}
                                    />
                                    <mesh
                                        name="Object_7"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_7 as THREE.Mesh).geometry}
                                        material={materials['Material.002']}
                                    />
                                    <mesh
                                        name="Object_8"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_8 as THREE.Mesh).geometry}
                                        material={materials.Space_Grey}
                                    />
                                    <mesh
                                        name="Object_9"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_9 as THREE.Mesh).geometry}
                                        material={materials['Space_Grey.001']}
                                    />
                                    <group
                                        name="Empty_1"
                                        position={[0, 0.001, 0]}
                                        rotation={[-Math.PI, 0, 0]}
                                        scale={[-0.039, 0.039, 0.039]}>
                                        <group
                                            name="Camera_Light_0"
                                            position={[0, 0.077, -0.044]}
                                            rotation={[-1.192, 0, 0]}
                                            scale={[-25.381, 25.381, 25.381]}>
                                            <mesh
                                                name="Object_12"
                                                castShadow
                                                receiveShadow
                                                geometry={(nodes.Object_12 as THREE.Mesh).geometry}
                                                material={materials.Camera_Light}
                                            />
                                        </group>
                                    </group>
                                </group>
                                <group name="Caps_Lock_Light_3" position={[0, -0.014, 0]} scale={0.275}>
                                    <mesh
                                        name="Object_14"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_14 as THREE.Mesh).geometry}
                                        material={materials.Caps_Lock_Light}
                                    />
                                </group>
                                <group
                                    name="Macbook_Pro_4"
                                    position={[0, 0.008, -0.104]}
                                    rotation={[1.949, 0, 0]}
                                    scale={0.275}>
                                    <mesh
                                        name="Object_16"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_16 as THREE.Mesh).geometry}
                                        material={materials['Material.001']}
                                    />
                                </group>
                                <group name="Main_Body_5" position={[0, -0.014, 0]} scale={0.275}>
                                    <mesh
                                        name="Object_18"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_18 as THREE.Mesh).geometry}
                                        material={materials.Space_Grey}
                                    />
                                    <mesh
                                        name="Object_19"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_19 as THREE.Mesh).geometry}
                                        material={materials.Black_Plastic}
                                    />
                                    <mesh
                                        name="Object_20"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_20 as THREE.Mesh).geometry}
                                        material={materials.Black_Plastic}
                                    />
                                    <mesh
                                        name="Object_21"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_21 as THREE.Mesh).geometry}
                                        material={materials['Keys.001']}
                                    />
                                </group>
                                <group name="Touch_Bar_6" position={[0, -0.014, 0]} scale={0.275}>
                                    <mesh
                                        name="Object_23"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_23 as THREE.Mesh).geometry}
                                        material={materials.Black_Plastic}
                                    />
                                    <mesh
                                        name="Object_24"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_24 as THREE.Mesh).geometry}
                                        material={materials.Black_Glass}
                                    />
                                    <mesh
                                        name="Object_25"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_25 as THREE.Mesh).geometry}
                                        material={materials.Keys}
                                    />
                                </group>
                                <group name="Touch_Bar_Shot_7" position={[0, -0.014, 0]} scale={0.275}>
                                    <mesh
                                        name="Object_27"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_27 as THREE.Mesh).geometry}
                                        material={materials['Touch_Bar_Shot_2021-04-02_at_18.13.28']}
                                    />
                                </group>
                                <group name="Keyboard_8" position={[0, -0.014, 0]} scale={0.275}>
                                    <mesh
                                        name="Object_29"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_29 as THREE.Mesh).geometry}
                                        material={materials.Black_Plastic}
                                    />
                                    <mesh
                                        name="Object_30"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_30 as THREE.Mesh).geometry}
                                        material={materials.Keys}
                                    />
                                </group>
                                <group name="Cube_9" position={[0, -0.014, 0]}>
                                    <mesh
                                        name="Object_32"
                                        castShadow
                                        receiveShadow
                                        geometry={(nodes.Object_32 as THREE.Mesh).geometry}
                                        material={materials.Black_Plastic}
                                    />
                                </group>
                                <group
                                    name="Circle001_12"
                                    position={[0.203, 0.008, -0.104]}
                                    rotation={[0.011, -0.75, 1.274]}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </Float>
    )
}
useGLTF.preload('/models/macbook.glb')
